apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: store-prod

resources:
  - ../../base

namePrefix: prod-

configMapGenerator:
  - name: store-config
    behavior: merge
    literals:
      - STORE_TITLE="Jeff's Flagship Store [PROD]"
      - CATALOG_ENV="production"

patches:
  - target:
      kind: Deployment
      name: store-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: catalog-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Ingress
      name: store-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: store.local
