apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - catalog-deployment.yaml
  - catalog-service.yaml
  - catalog-hpa.yaml

configMapGenerator:
  - name: store-config
    literals:
      - STORE_TITLE="Default Store"
      - CATALOG_ENV="base"

secretGenerator:
  - name: store-secrets
    literals:
      - CATALOG_API_KEY="base-catalog-secret-key"
