---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: store-secrets
  namespace: default
spec:
  encryptedData:
    CATALOG_API_KEY: AgCdNHq3/v5VFXq+R9P4MEoo/4StWmIHzN4rsl6qqvjBf2n7u7c7YL1Ltx0BJ+h17noDO6fwKYqDtOP6/AWxJ5bKjL4GNHCzpkouWLcJwxDC8Dx5016rtV3nTGiMeo8j6bQ+0woXZ53vOx8uKbhag5JWNhBaphLr5CfuQ5CQ3GQvrFf28gbk3ME6zyrj5mG+eObSDvSHawfsvbKo4tKXKxT1blGUbCumK6DsMhxmOuLRzfdrMekEJIw2pVSEbDeyWnaLgnhRM0Led0nqYWf/sGQlZwFfIweJxxaLmPk8Zi717kDCtjpU/UZ/giom7XL07u0Xj4bxRkyQSk32a/tJ2oTl9566govLYuJq73RWyX3w/kKL+7b/rGeCvskGOUKRfvMy003GQFqGURhQJsAby1CCuIeu3N2jDELvpV5o7M1bmciuA25j25FIFrCRIX6BPcqmlM2qC+884JnOhgmx+CkBGEr4ygzbm0ahPm9l1gXhoXfWPfZA9ImrF3cP0DiVFSZqLR1HU4KP23+krU++gO0iFnOO5vRck7CB1xUv1zPg2vI1roU/OO1ilLdmBd6mnPN4hUdn+EHoHF/XmWSujfxo7b3gr4R83/8mGsrs9upDqwj48rP/MmeJHmT1Y0eivmcVa+O03jg3lB0V0Q+SK9nj07kLaHgavCypdlbdHX9PijqrHzRjrjSNQh8dIgHXX0GL8H2XFgXyl6F+FPPcT70u6y7VXFonLjnjcxI=
  template:
    metadata:
      creationTimestamp: null
      name: store-secrets
      namespace: default
