---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: store-secrets
spec:
  encryptedData:
    CATALOG_API_KEY: AgCDoGBBIjZNCxIwTLx6W91+pXhv09uWtIIy+Ug1byEvfy7GMJt9FUzXVeslJT0eT8mryV5vrVf8bHK3zqzfM3JhBsIVogyDpAX8cEGpP4aZlAhi/8M5k1ZdJF6kwjjL7olyKCFa4NbhmKRZu0D/Qaty4D9XHgX3+RbHRtvPW1VBer8srLWIkRnQnjrsLXIygrvGo55qDXfPt6sKG67VuPiebxu/ooPKR1Cc1gFI70brF6bx/6fPbMz5mFAORxy3wN1XLa5Z30VQ2dUyLdxyClremq90rHjdO4A/oGCG0bvYUtPXumtNAqcTh6fa0JJFICxHlUBFfL6onzsWOpijd2/tb848rfvuy3ZMMi0YouAGRJt9948/lwXXUhlLM+Nuvt3VepNeoOoQhHsEMSprpR+So+7KXcQxCFNa1ZTcgnSFcfxNHzaUoyeMW42co6+U+aT7O53RJbmMawki8HLYM9k8przEscj6Vi9/y4/Sk/Z+1vaCcDorIXjd4t4/HmNIHYyAnl1XZv53jReDTCwUQz/DJsa2EhMedvTgzQV7s2oNHPIPAmaKHgXnmUAJrh12X8BXRK7wFIQ++i4uaDtDNpXrX1xEb9jrru/UatF3wcs5KBDMv2oDOyqix7O3VSwqdnfUWtiHIPynm5zNWQSEL9OCDf9Vo263X77E9SuTUj4RlHwTD+9Dwe37PLV/xw+a6pF1+Q9PhczVKLP31v5qe0rBKQF8F3lNQGa/WZs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: store-secrets
