apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  template:
    spec:
      containers:
        - name: catalog-api
          args:
            - "-text=# HELP catalog_items_total Total items in catalog\n# TYPE catalog_items_total gauge\ncatalog_items_total 0\n# HELP catalog_up Catalog service health status\n# TYPE catalog_up gauge\ncatalog_up 0\n"
          envFrom:
            - configMapRef:
                name: store-config
            - secretRef:
                name: dev-store-secrets
