apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: store-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - target:
      kind: Deployment
      name: store-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Ingress
      name: store-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.store.local
