name: GitOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-manifests:
    name: Validate & Dry-Run Kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Validate Base Manifests
        run: |
          echo "Validating k8s/base..."
          kubectl kustomize k8s/base > /dev/null

      - name: Validate Dev Overlay
        run: |
          echo "Validating k8s/overlays/dev..."
          kubectl kustomize k8s/overlays/dev > dev-build.yaml
          grep -q "dev.store.local" dev-build.yaml

      - name: Validate Prod Overlay
        run: |
          echo "Validating k8s/overlays/prod..."
          kubectl kustomize k8s/overlays/prod > prod-build.yaml
          grep -q "store.local" prod-build.yaml

      - name: Client-side Dry Run Validation
        run: |
          echo "Running client dry-run on generated manifests..."
          kubectl apply --dry-run=client -f dev-build.yaml
          kubectl apply --dry-run=client -f prod-build.yaml
